// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogpostDocumentDataSlicesSlice = never;

/**
 * Content for Blogpost documents
 */
interface BlogpostDocumentData {
  /**
   * Slice Zone field in *Blogpost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Description field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type ContactDocumentDataSlicesSlice =
  | ContactFormSlice
  | SectionGallerySlice
  | SinglePageHeaderSlice
  | CtaSectionSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type EventsDocumentDataSlicesSlice = EventItemSlice;

/**
 * Content for Events documents
 */
interface EventsDocumentData {
  /**
   * Title field in *Events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice>;
}

/**
 * Events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventsDocumentData>, "events", Lang>;

/**
 * Item in *Footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * Title field in *Footer → Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Footer → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Socials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | CtaSectionSlice
  | SectionGallerySlice
  | SectionShareSlice
  | SectionAboutSlice
  | EventsSectionSlice
  | SectionScrollTextSlice
  | CustomerLogosSlice
  | SectionHeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type JoinUsDocumentDataSlicesSlice =
  | SignUpFormSlice
  | SectionGallerySlice
  | SinglePageHeaderSlice;

/**
 * Content for Join us documents
 */
interface JoinUsDocumentData {
  /**
   * Slice Zone field in *Join us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<JoinUsDocumentDataSlicesSlice> /**
   * Meta Title field in *Join us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: join_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Join us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: join_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Join us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Join us document from Prismic
 *
 * - **API ID**: `join_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JoinUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JoinUsDocumentData>,
    "join_us",
    Lang
  >;

/**
 * Item in *Navigation → Buttons*
 */
export interface NavigationDocumentDataButtonsItem {
  /**
   * Link field in *Navigation → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.buttons[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Title field in *Navigation → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.buttons[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Variant field in *Navigation → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<
    | "primary"
    | "secondary"
    | "tertiary"
    | "secondary-bleek-lime"
    | "primary-bleek-lime"
  >;
}

type NavigationDocumentDataSlicesSlice = NavigationSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Dark mode field in *Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: navigation.dark_mode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dark_mode: prismic.BooleanField;

  /**
   * Buttons field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttons: prismic.GroupField<Simplify<NavigationDocumentDataButtonsItem>>;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

export type AllDocumentTypes =
  | BlogpostDocument
  | ContactDocument
  | EventsDocument
  | FooterDocument
  | HomeDocument
  | JoinUsDocument
  | NavigationDocument;

/**
 * Item in *ContactForm → Default → Primary → Sidebar content*
 */
export interface ContactFormSliceDefaultPrimarySidebarItem {
  /**
   * Title field in *ContactForm → Default → Primary → Sidebar content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.sidebar[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ContactForm → Default → Primary → Sidebar content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.sidebar[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Description field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Sidebar content field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.sidebar[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sidebar: prismic.GroupField<
    Simplify<ContactFormSliceDefaultPrimarySidebarItem>
  >;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Title field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Primary button title field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.primary_button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_title: prismic.KeyTextField;

  /**
   * Primary button link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary button title field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.secondary_button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_title: prismic.KeyTextField;

  /**
   * Secondary button link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *SectionSponsors → Default → Primary*
 */
export interface CustomerLogosSliceDefaultPrimary {
  /**
   * Title field in *SectionSponsors → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SectionSponsors → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button field in *SectionSponsors → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *SectionSponsors → Items*
 */
export interface CustomerLogosSliceDefaultItem {
  /**
   * Image field in *SectionSponsors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *SectionSponsors → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Tier field in *SectionSponsors → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_logos.items[].tier
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tier: prismic.SelectField<"1" | "2" | "3">;
}

/**
 * Default variation for SectionSponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomerLogosSliceDefaultPrimary>,
  Simplify<CustomerLogosSliceDefaultItem>
>;

/**
 * Slice variation for *SectionSponsors*
 */
type CustomerLogosSliceVariation = CustomerLogosSliceDefault;

/**
 * SectionSponsors Shared Slice
 *
 * - **API ID**: `customer_logos`
 * - **Description**: CustomerLogos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerLogosSlice = prismic.SharedSlice<
  "customer_logos",
  CustomerLogosSliceVariation
>;

/**
 * Primary content in *EventItem → Default → Primary*
 */
export interface EventItemSliceDefaultPrimary {
  /**
   * Title field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_item.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Start date field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event_item.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End date field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event_item.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Description field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_item.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Location field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_item.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;

  /**
   * Visible field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: event_item.default.primary.visible
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  visible: prismic.BooleanField;
}

/**
 * Default variation for EventItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventItem*
 */
type EventItemSliceVariation = EventItemSliceDefault;

/**
 * EventItem Shared Slice
 *
 * - **API ID**: `event_item`
 * - **Description**: EventItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventItemSlice = prismic.SharedSlice<
  "event_item",
  EventItemSliceVariation
>;

/**
 * Primary content in *EventsSection → Default → Primary*
 */
export interface EventsSectionSliceDefaultPrimary {
  /**
   * Title field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Events field in *EventsSection → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events_section.default.primary.events
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  events: prismic.ContentRelationshipField;
}

/**
 * Default variation for EventsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventsSection*
 */
type EventsSectionSliceVariation = EventsSectionSliceDefault;

/**
 * EventsSection Shared Slice
 *
 * - **API ID**: `events_section`
 * - **Description**: EventsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSectionSlice = prismic.SharedSlice<
  "events_section",
  EventsSectionSliceVariation
>;

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationSliceDefaultPrimary {
  /**
   * Title field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationSliceDefaultItem {
  /**
   * Child title field in *NavigationItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].child_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  child_title: prismic.KeyTextField;

  /**
   * Child link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationSliceDefaultPrimary>,
  Simplify<NavigationSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationSliceVariation = NavigationSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation`
 * - **Description**: Navigation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationSlice = prismic.SharedSlice<
  "navigation",
  NavigationSliceVariation
>;

/**
 * Primary content in *SectionAbout → Default → Primary*
 */
export interface SectionAboutSliceDefaultPrimary {
  /**
   * Title field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Most solar boat teams outsource over 80% of   their components.  We don’t.
   * - **API ID Path**: section_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Card title field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_about.default.primary.card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card description field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_about.default.primary.card_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_description: prismic.RichTextField;

  /**
   * Buttons field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_about.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      | "primary"
      | "secondary"
      | "primary-bleek-lime"
      | "tertiary"
      | "secondary-bleek-lime"
    >
  >;

  /**
   * Image field in *SectionAbout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SectionAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionAbout*
 */
type SectionAboutSliceVariation = SectionAboutSliceDefault;

/**
 * SectionAbout Shared Slice
 *
 * - **API ID**: `section_about`
 * - **Description**: SectionAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionAboutSlice = prismic.SharedSlice<
  "section_about",
  SectionAboutSliceVariation
>;

/**
 * Primary content in *SectionGallery → Default → Primary*
 */
export interface SectionGallerySliceDefaultPrimary {
  /**
   * Title field in *SectionGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SectionGallery → Items*
 */
export interface SectionGallerySliceDefaultItem {
  /**
   * Image field in *SectionGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Width field in *SectionGallery → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: large
   * - **API ID Path**: section_gallery.items[].width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  width: prismic.SelectField<"large" | "medium" | "small", "filled">;
}

/**
 * Default variation for SectionGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionGallerySliceDefaultPrimary>,
  Simplify<SectionGallerySliceDefaultItem>
>;

/**
 * Slice variation for *SectionGallery*
 */
type SectionGallerySliceVariation = SectionGallerySliceDefault;

/**
 * SectionGallery Shared Slice
 *
 * - **API ID**: `section_gallery`
 * - **Description**: SectionGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionGallerySlice = prismic.SharedSlice<
  "section_gallery",
  SectionGallerySliceVariation
>;

/**
 * Primary content in *SectionHero → Default → Primary*
 */
export interface SectionHeroSliceDefaultPrimary {
  /**
   * Title field in *SectionHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Inventing Tomorrow, Racing Today
   * - **API ID Path**: section_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SectionHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Cta field in *SectionHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Let's go!
   * - **API ID Path**: section_hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * Video field in *SectionHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: section_hero.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Poster field in *SectionHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_hero.default.primary.poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  poster: prismic.ImageField<never>;
}

/**
 * Default variation for SectionHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionHero*
 */
type SectionHeroSliceVariation = SectionHeroSliceDefault;

/**
 * SectionHero Shared Slice
 *
 * - **API ID**: `section_hero`
 * - **Description**: SectionHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionHeroSlice = prismic.SharedSlice<
  "section_hero",
  SectionHeroSliceVariation
>;

/**
 * Primary content in *SectionScrollText → Default → Primary*
 */
export interface SectionScrollTextSliceDefaultPrimary {
  /**
   * Highlighted title field in *SectionScrollText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_scroll_text.default.primary.highlighted_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  highlighted_title: prismic.KeyTextField;

  /**
   * title field in *SectionScrollText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_scroll_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for SectionScrollText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionScrollTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionScrollTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionScrollText*
 */
type SectionScrollTextSliceVariation = SectionScrollTextSliceDefault;

/**
 * SectionScrollText Shared Slice
 *
 * - **API ID**: `section_scroll_text`
 * - **Description**: SectionScrollText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionScrollTextSlice = prismic.SharedSlice<
  "section_scroll_text",
  SectionScrollTextSliceVariation
>;

/**
 * Primary content in *SectionShare → Default → Primary*
 */
export interface SectionShareSliceDefaultPrimary {
  /**
   * Title field in *SectionShare → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SectionShare → Items*
 */
export interface SectionShareSliceDefaultItem {
  /**
   * Category title field in *SectionShare → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].category_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_title: prismic.KeyTextField;

  /**
   * Category image field in *SectionShare → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].category_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  category_image: prismic.ImageField<never>;

  /**
   * CTA title field in *SectionShare → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA description field in *SectionShare → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].cta_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_description: prismic.RichTextField;

  /**
   * CTA button link field in *SectionShare → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].cta_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA button title field in *SectionShare → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_share.items[].cta_button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button_title: prismic.KeyTextField;
}

/**
 * Default variation for SectionShare Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionShareSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionShareSliceDefaultPrimary>,
  Simplify<SectionShareSliceDefaultItem>
>;

/**
 * Slice variation for *SectionShare*
 */
type SectionShareSliceVariation = SectionShareSliceDefault;

/**
 * SectionShare Shared Slice
 *
 * - **API ID**: `section_share`
 * - **Description**: SectionShare
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionShareSlice = prismic.SharedSlice<
  "section_share",
  SectionShareSliceVariation
>;

/**
 * Primary content in *SignUpForm → Default → Primary*
 */
export interface SignUpFormSliceDefaultPrimary {
  /**
   * Description field in *SignUpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Terms and conditions field in *SignUpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sign_up_form.default.primary.terms_and_conditions
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  terms_and_conditions: prismic.RichTextField;
}

/**
 * Default variation for SignUpForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SignUpFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SignUpFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SignUpForm*
 */
type SignUpFormSliceVariation = SignUpFormSliceDefault;

/**
 * SignUpForm Shared Slice
 *
 * - **API ID**: `sign_up_form`
 * - **Description**: SignUpForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SignUpFormSlice = prismic.SharedSlice<
  "sign_up_form",
  SignUpFormSliceVariation
>;

/**
 * Primary content in *SinglePageHeader → Default → Primary*
 */
export interface SinglePageHeaderSliceDefaultPrimary {
  /**
   * Eyebrow field in *SinglePageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_page_header.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *SinglePageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_page_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Tag field in *SinglePageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_page_header.default.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Image field in *SinglePageHeader → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_page_header.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Tag color field in *SinglePageHeader → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Bleek Lime
   * - **API ID Path**: single_page_header.default.primary.tag_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tag_color: prismic.SelectField<
    "Bleek Lime" | "Tidal Turqoise" | "EHBOrange",
    "filled"
  >;
}

/**
 * Default variation for SinglePageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SinglePageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SinglePageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SinglePageHeader*
 */
type SinglePageHeaderSliceVariation = SinglePageHeaderSliceDefault;

/**
 * SinglePageHeader Shared Slice
 *
 * - **API ID**: `single_page_header`
 * - **Description**: SinglePageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SinglePageHeaderSlice = prismic.SharedSlice<
  "single_page_header",
  SinglePageHeaderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialsItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      JoinUsDocument,
      JoinUsDocumentData,
      JoinUsDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataButtonsItem,
      NavigationDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimarySidebarItem,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      CustomerLogosSlice,
      CustomerLogosSliceDefaultPrimary,
      CustomerLogosSliceDefaultItem,
      CustomerLogosSliceVariation,
      CustomerLogosSliceDefault,
      EventItemSlice,
      EventItemSliceDefaultPrimary,
      EventItemSliceVariation,
      EventItemSliceDefault,
      EventsSectionSlice,
      EventsSectionSliceDefaultPrimary,
      EventsSectionSliceVariation,
      EventsSectionSliceDefault,
      NavigationSlice,
      NavigationSliceDefaultPrimary,
      NavigationSliceDefaultItem,
      NavigationSliceVariation,
      NavigationSliceDefault,
      SectionAboutSlice,
      SectionAboutSliceDefaultPrimary,
      SectionAboutSliceVariation,
      SectionAboutSliceDefault,
      SectionGallerySlice,
      SectionGallerySliceDefaultPrimary,
      SectionGallerySliceDefaultItem,
      SectionGallerySliceVariation,
      SectionGallerySliceDefault,
      SectionHeroSlice,
      SectionHeroSliceDefaultPrimary,
      SectionHeroSliceVariation,
      SectionHeroSliceDefault,
      SectionScrollTextSlice,
      SectionScrollTextSliceDefaultPrimary,
      SectionScrollTextSliceVariation,
      SectionScrollTextSliceDefault,
      SectionShareSlice,
      SectionShareSliceDefaultPrimary,
      SectionShareSliceDefaultItem,
      SectionShareSliceVariation,
      SectionShareSliceDefault,
      SignUpFormSlice,
      SignUpFormSliceDefaultPrimary,
      SignUpFormSliceVariation,
      SignUpFormSliceDefault,
      SinglePageHeaderSlice,
      SinglePageHeaderSliceDefaultPrimary,
      SinglePageHeaderSliceVariation,
      SinglePageHeaderSliceDefault,
    };
  }
}
