// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_section: dynamic(() => import("./CtaSection")),
  customer_logos: dynamic(() => import("./SectionSponsors")),
  event_item: dynamic(() => import("./EventItem")),
  events_section: dynamic(() => import("./EventsSection")),
  navigation: dynamic(() => import("./NavigationItem")),
  section_about: dynamic(() => import("./SectionAbout")),
  section_gallery: dynamic(() => import("./SectionGallery")),
  section_hero: dynamic(() => import("./SectionHero")),
  section_scroll_text: dynamic(() => import("./SectionScrollText")),
  section_share: dynamic(() => import("./SectionShare")),
  single_page_header: dynamic(() => import("./SinglePageHeader")),
};
